### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by joostmeijles** [patrickedqvist/wait-for-vercel-preview#23]
I have the following job:
```
test_setup:
    name: Test setup
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
    - name: Waiting for Vercel preview deployment to be ready
      uses: patrickedqvist/wait-for-vercel-preview@v1.1.0
      id: waitForVercelPreviewDeployment
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        max_timeout: 360    
        check_interval: 2
```

which fails with a `Cannot read property 'get' of undefined` error:
![image](https://user-images.githubusercontent.com/4342282/121335326-c5374b00-c91a-11eb-8c70-9210444aeab1.png)

Please note that the job worked before. For example v1.0.4 is still working for me.

Any clues?
