### ISSUE TITLE
Parallelization?

### ISSUE THREAD

**Issue by kylemh** [patrickedqvist/wait-for-vercel-preview#24]
I'm nearly off and running except only the last container actually runs my tests. Any idea how I can split them? Maybe I should separate into 2 jobs and conditionally run one only after wait-for-vercel-preview is green?

I figure this would be helpful for others that use your hook.

```yaml
name: CI

on: [pull_request]

jobs:
  Cypress:
    runs-on: ubuntu-latest
    strategy:
      # DO NOT cancel other containers on fail, because Cypress processes die leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Use Node with version in .nvmrc
        uses: actions/setup-node@v2
        with:
          always-auth: true
          registry-url: https://registry.npmjs.org
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - uses: actions/cache@v2
        with:
          key: cache-${{ hashFiles('yarn.lock') }}
          path: |
            node_modules
            ~/.cache/yarn
            ~/.cache/Cypress
      - name: Install dependencies
        run: yarn --non-interactive --frozen-lockfile --silent
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Wait for Preview Deployment
        uses: patrickedqvist/wait-for-vercel-preview@v1.1.1
        id: waitForPreview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 360
          environment: Preview – website

      - run: echo ${{ steps.waitForPreview.outputs.url }}

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: 'yarn test:cy:record --config baseUrl=${{ steps.waitForPreview.outputs.url }}'
          parallel: true
        env:
          CYPRESS_NEXT_PUBLIC_AMPLIFY_STAGE: dev
```
