### ISSUE TITLE
Error: Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by Shelob9** [patrickedqvist/wait-for-vercel-preview#3]
I have the Vercel Github integration setup.  I am getting the error in my log for this step. I tried changing "uses" to "patrickedqvist/wait-for-vercel-preview@master" and got the same error. 
Possibly related to #1 

### Workflow
```yml
name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/patrickedqvist/wait-for-vercel-preview
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@4b65b428ac75b54f43f45599d757b9d3d68e17fd
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
      - uses: actions/checkout@v2
      - name: Install
        run: yarn
      - name: Run tests
        run: yarn test --ci
```

### Build Log

```sh
 Waiting for 200 from the Vercel Preview0s
    max_timeout: 60
Run patrickedqvist/wait-for-vercel-preview@4b65b428ac75b54f43f45599d757b9d3d68e17fd
  with:
    token: ***
    max_timeout: 60
##[error]Cannot read property 'number' of undefined
```
