### ISSUE TITLE
Output host?

### ISSUE THREAD

**Issue by jasonkuhrt** [patrickedqvist/wait-for-vercel-preview#39]
```yaml
  await-fox-deployment:
    runs-on: ubuntu-latest
    outputs:
      url: ${{steps.format-outputs.outputs.url}}
      host: ${{steps.format-outputs.outputs.host}}
    steps:
      - name: Wait for Fox deployment
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        id: await-fox-deployment
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          max_timeout: 600 # 10 minutes
          check_interval: 10
      - name: Format Outputs
        id: format-outputs
        run: |
          if [[ '${{steps.await-fox-deployment.outputs.url}}' == https://* ]]; then
            host=$(echo '${{steps.await-fox-deployment.outputs.url}}' | cut -c 9-)
          else
            host='${{steps.await-fox-deployment.outputs.url}}'
          fi

          echo "::set-output name=url::${{steps.await-fox-deployment.outputs.url}}"
          echo "::set-output name=host::${host}"

```

I currently use the above code to output the host in addition to the URL. Would you be willing to have host as a built in output?
