### ISSUE TITLE
Support multiple preview deployments per Pull request

### ISSUE THREAD

**Issue by MarkLyck** [patrickedqvist/wait-for-vercel-preview#47]
This action works great for projects with a single Vercel deployment.

But in my case my project has 3 vercel deployments per project, and currently this action only returns the URL for the first one that runs which is random.

I would like to either have it run on all preview deployments when they are succesful or a specific one. But this doesn't seem to be supported.

**Comment by nc** [comment]
Any plans to fix this @patrickedqvist we'd be happy to sponsor you if this is fixed :)

**Comment by pip8786** [comment]
@MarkLyck we're able to wait on a specific environment by doing this:
```
steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
          environment: Preview – web-app
```
We have 2 deployments that happens each time, but currently only interested in running on a specific one. I'm not sure about running on all of them though, maybe that would require separate actions? 

Edit to add: here's the line where it passes the environment to octokit: https://github.com/patrickedqvist/wait-for-vercel-preview/blob/c934e81c4b18ad59acbb866fb817ed586b17ecba/action.js#L218 which I believe is this API: https://docs.github.com/en/rest/deployments/deployments?apiVersion=2022-11-28#list-deployments
