### ISSUE TITLE
New node18 error with latest release

### ISSUE THREAD

**Issue by jasonkuhrt** [patrickedqvist/wait-for-vercel-preview#53]
Getting this error with the latest release:

<img width="1173" alt="CleanShot 2023-01-30 at 09 47 23@2x" src="https://user-images.githubusercontent.com/284476/215509520-66eb2b2e-126a-42ba-bb7f-4af30b190f53.png">

Workflow code:

```
name: await-vercel-deployment
on:
  workflow_call:
    outputs:
      url:
        description: Full URL of the deployment
        value: ${{jobs.run.outputs.url}}
      host:
        description: Host name of the URL of the deployment
        value: ${{jobs.run.outputs.host}}
jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      url: ${{steps.format-outputs.outputs.url}}
      host: ${{steps.format-outputs.outputs.host}}
    steps:
      - name: Wait for Vercel deployment
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.0
        id: await-vercel-deployment
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          max_timeout: 1200 # 20 minutes
          check_interval: 20
      - name: Format Outputs
        id: format-outputs
        run: |
          if [[ '${{steps.await-vercel-deployment.outputs.url}}' == https://* ]]; then
            host=$(echo '${{steps.await-vercel-deployment.outputs.url}}' | cut -c 9-)
          else
            host='${{steps.await-vercel-deployment.outputs.url}}'
          fi
          echo "::set-output name=url::${{steps.await-vercel-deployment.outputs.url}}"
          echo "::set-output name=host::${host}"

```

We are not using Node 18... 🤔
