### ISSUE TITLE
Actor name is not `vercel[bot]`

### ISSUE THREAD

**Issue by GRA0007** [patrickedqvist/wait-for-vercel-preview#56]
Not sure if Vercel have changed how deployments work, but checking the GitHub deployment for a specific sha reveals that the `creator.login` field is set to my username, not `vercel[bot]`.

https://github.com/patrickedqvist/wait-for-vercel-preview/blob/bfdff514ff78a669f2536e9f4dd4ef5813a704a2/action.js#L329

Is it important that the deployments are filtered by this username?

https://github.com/patrickedqvist/wait-for-vercel-preview/blob/bfdff514ff78a669f2536e9f4dd4ef5813a704a2/action.js#L223-L225

**Comment by jy95** [comment]
I noticed recently that behavior as well and so detection of my preview deployments failed

![image](https://github.com/patrickedqvist/wait-for-vercel-preview/assets/9306961/4c473e32-7574-48eb-9641-a1c52ba63e8f)

**Comment by Emiltayeb** [comment]
did you find a solution?
any progress?

**Comment by victorcarvalhosp** [comment]
I'm getting the same error here:

`Could not find any deployments for actor vercel[bot], retrying (attempt 90 / 90)`

Did you find a workaround for this?

**Comment by RyanClementsHax** [comment]
I came by a similar problem, but after diving in further, at least for me, the problem was because I didn't give the workflow the required [permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) to run. It seems that because I specified other permissions, by default, everything else is denied, so I had to manually add them back in.

I needed to add this to my workflow file.

```diff
permissions:
  pull-requests: write
+  checks: read
+  contents: read
+  deployments: read
```

Does that fix y'all's issues?

**Comment by peterb0yd** [comment]
Bump, I'm still seeing this and @RyanClementsHax's suggested workaround doesn't fix it 😕

**Comment by goooseman** [comment]
Actually for me the fix is working, using the following permissions:

```
jobs:
  lighthouse-on-vercel-preview:
    runs-on: ubuntu-latest

    # Needed so the action can read the repo and write PR comments
    permissions:
      contents: read
      pull-requests: write
      checks: read
      deployments: read
      statuses: read
```

And also had to disable Vercel -> App -> Settings -> Deployment protection to avoid 401s
