### ISSUE TITLE
Document which permissions are required for this action

### ISSUE THREAD

**Issue by Jacob-Roberts** [patrickedqvist/wait-for-vercel-preview#66]
From my basic testing I believe this is all that is required to get this action to work:

```yaml
jobs:
  jobname:
    permissions:
      contents: read
      pull-requests: read
      deployments: read
    steps:
       ...
```

This should resolve the issue of `resource not accessible by integration` in github actions
