### ISSUE TITLE
Unexpected input  vercel_protection_bypass_header

### ISSUE THREAD

**Issue by beelarr** [patrickedqvist/wait-for-vercel-preview#75]
---

### Issue Details

**Environment:**
- **App:** Next.js v14.2.12
- **Context:** A protection bypass for automation secret is set in Vercel and copied over to my GitHub Secrets but it doesn't seem to be working in the action. 

---

**GitHub Action Snippet:**

```yaml
- name: Waiting on the Vercel Preview
  uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
  id: waitForDeploy
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    vercel_protection_bypass_header: ${{ secrets.VERCEL_PREVIEW_BYPASS_AUTH }}
    max_timeout: 300
```

---

**Problem:**

When running this action, I encounter the following warning:

```
Warning: Unexpected input(s) 'vercel_protection_bypass_header', valid inputs are ['token', 'max_timeout', 'environment', 'allow_inactive', 'check_interval', 'vercel_password', 'path']
```

Despite this, the action continues, but returns `401` errors on each of the 150 iterations, which leads me to think that something might be broken.

The input `vercel_protection_bypass_header` seems valid based on the `README` and the `action.js` file, but it isn't recognized.

---

**Request:**

Any suggestions or insights into resolving this issue would be greatly appreciated!

**Comment by beelarr** [comment]
An update,  I had my secret setup incorrectly.  However I still see the warning from this action.

**Comment by patrickedqvist** [comment]
@beelarr That is probably because in that version the "vercel_protection_bypass_header" option is not documented in the action.yml. Therefore Github gives you that warning. It does however exist in the code and should work as expected.

**Comment by vilkg** [comment]
Hi! I have the same issue with the newest 1.3.2 version. Seems like the feature was merged in end of August, but latest action version was released in July.

**Comment by beelarr** [comment]
Thanks @patrickedqvist !

@vilkg It seems that Vercel has updated some of their [Protection Bypass for Automation](https://vercel.com/docs/security/deployment-protection/methods-to-bypass-deployment-protection/protection-bypass-automation#protection-bypass-for-automation) and this action currently doesn't work with the bypass header.  If I get a few minutes I will look into fixing this.

**Comment by patrickedqvist** [comment]
@beelarr Can you test the canary branch? A lot has changed in that branch so you want to review the readme again, especially the migrate section. All you probably need to do is to change the vercel header input from `vercel_protection_bypass_header` to `vercel_protection_bypass_secret`.

**Comment by beelarr** [comment]
> @beelarr Can you test the canary branch? A lot has changed in that branch so you want to review the readme again, especially the migrate section. All you probably need to do is to change the vercel header input from `vercel_protection_bypass_header` to `vercel_protection_bypass_secret`.

Sure, I'll give it a try.

**Comment by beelarr** [comment]
@patrickedqvist Canary works great!!  

If anyone else is following along here is my setup:

```
- name: Waiting on the Vercel Preview
uses: patrickedqvist/wait-for-vercel-preview@canary
id: waitForDeploy
with:
  token: ${{ secrets.GITHUB_TOKEN }}
  vercel_protection_bypass_secret: ${{ env.VERCEL_PREVIEW_BYPASS_AUTH }}
  max_attempts: 20
  retry_interval: 5
```

I'll be looking for the v2 release. Reach out if I can ever help with anything and thank you for working on this!!
